# fly.toml app configuration file generated for fcr-web on 2023-08-25T16:14:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fcr-web"
primary_region = "gig"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "30s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false
